---
# ====== Application: Pousada do Ypuã v2.2 ===================
identification: 
  name: Pousada do Ypuã v2.2
  alias: POUSADADOYPUA-2-2
  version: Release 2.2

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 2236516100255260877

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_MARCIOSENAI

globalization: 
  primary-language: Portuguese (Brazil) (pt-br)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DD-MON-YYYY
  timestamp: DD-MON-YYYY
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_FILES#app-208491-logo.png'
  text: Pousadadoypua

progressive-web-app: 
  enable: true
  installable: true
  display: Fullscreen
  screen-orientation: Any
  theme-color: '#f42b2b'
  ios-status-bar-style: Default
  app-description: Sistema de Gestão de Hospedagem
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 2236516949042260878

navigation-bar: 
  implementation: List
  list: Navigation Bar # 2237406570207261153
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Pousadadoypua 2.2

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 2236511943742260874
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15538079930269

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 2236512208797260874
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15538079930270

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 2236512541129260875
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15538079930271

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 2236512808091260875
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15538079930272

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 2236513171347260875
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15538079930273

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 2236513416191260875
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15538079930276

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 2236513766357260875
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15538079930277

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 2236514098038260876
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15538079930281

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 2236514338740260876
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15538079930283

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 2236514631387260876
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15538079930285

- # ====== Component Setting: NATIVE_IR ========================
  id: 2236514952826260876
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15538079930291

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 2236515228212260876
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15538079930295

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 2236515539836260877
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15538079930295

